FROM node:22-alpine AS builder

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install --omit=dev

COPY . .

FROM node:22-alpine

WORKDIR /app

COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/.env.example ./.env.example # Copia la plantilla de entorno
COPY --from=builder /app/src ./src

EXPOSE 5000 # Usa el puerto por defecto de Express o el que uses en tu .env

CMD ["npm", "start"]