FROM node:22-alpine AS builder

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm install --omit=dev

COPY . .

FROM node:22-alpine

WORKDIR /app

COPY --from=builder /app .

EXPOSE 5000

CMD ["npm", "start"]