services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile 
    
    ports:
      - "3000:80" 
    
    depends_on:
      - backend
    
    environment:
      VITE_API_BASE_URL: http://backend:5000/api

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000" 
    depends_on:
      - db
    environment:
      - PORT=5000 
      - MONGO_URI=mongodb://db:27017/user_management_db 
      - JWT_SECRET=tu_secreto_super_secreto_y_largo
      - JWT_EXPIRE=1d
  db:
    image: mongo:latest 
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=user_management_db 
volumes:
  mongo_data: