services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile 
    
    ports:
      - "80:80" 
    
    depends_on:
      - backend
    
    restart: unless-stopped

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile

    ports:
      - "5000:5000" 
    depends_on:
      - db
    
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@db:27017/${MONGO_DB}?authSource=admin
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRE=${JWT_EXPIRE}
      - ADMIN_NAME=${ADMIN_NAME}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    restart: unless-stopped

  db:
    image: mongo:latest 
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_DB}
    restart: unless-stopped

volumes:
  mongo_data: