name: Auto deploy to EC2 (main branch)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Auto deploy to EC2
    runs-on: ubuntu-latest 

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: us-east-1 

      - name: EC2 SSH Deployment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.EC2_SSH_PASSPHRASE }}
          script: |
            set -e

            cd /home/ubuntu/app

            echo ">>> 1. Limpiando estado de Git y obteniendo última versión del código..."
            git fetch origin
            git reset --hard origin/main
            git clean -fdx

            echo ">>> 2. Sincronizando secretos desde AWS Secrets Manager..."
            SECRET_ID="app/user-management/prod"
            AWS_REGION="us-east-1"
            SECRET_JSON=$(aws secretsmanager get-secret-value --secret-id $SECRET_ID --region $AWS_REGION --query SecretString --output text)
            
            ENV_FILE="/home/ubuntu/app/infrastructure/.env.docker.temp"
            echo "$SECRET_JSON" | jq -r 'to_entries|map("\(.key)=\(.value|tostring)")|.[]' > "$ENV_FILE"

            cd /home/ubuntu/app/infrastructure

            echo ">>> 3. Reconstruyendo y reiniciando servicios..."
            sudo docker compose --env-file "$ENV_FILE" up --build --force-recreate -d

            echo ">>> 4. Esperando a que la base de datos esté operativa"
            sleep 20 # Damos un poco de tiempo para que la DB se estabilice
            echo ">>> 5. Running seed script..."
            sudo docker compose --env-file "$ENV_FILE" exec -T backend npm run seed || true

            echo ">>> 6. Limpiando imágenes antiguas de Docker"
            sudo docker image prune -af
